### ISSUE TITLE
React DOM 15.2 Add warning for unknown properties on DOM elements

### ISSUE THREAD

**Issue by twDuke** [reactionic/reactionic#66]
Warnings in console with latests react-dom

Anything we need to do to fix it from here?

Unknown props `customClasses`, `leftButton`, `rightButton`, `history`, `location`, `params`, `route`, `routeParams`, `routes`, `pageList`, `isFetching`, `navigate` on <span> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in span (created by ReactTransitionGroup)
    in ReactTransitionGroup (created by ReactCSSTransitionGroup)
    in ReactCSSTransitionGroup (created by RouteCSSTransitionGroup)
    in RouteCSSTransitionGroup (created by IonNavBar)
    in div (created by IonNavBar)
    in IonNavBar (created by Layout)
    in div (created by IonSideMenuContent)
    in IonSideMenuContent (created by Layout)
    in div (created by IonSideMenuContainer)
    in IonSideMenuContainer (created by Layout)
    in Layout (created by Connect(Layout))
    in Connect(Layout) (created by RouterContext)
    in div (created by IonBody)
    in IonBody (created by App)
    in App (created by RouterContext)
    in RouterContext (created by Router)
    in Router (created by AppRouter)
    in AppRouter
    in Provider

https://github.com/facebook/react/releases

**Comment by DarrylD** [comment]
Also having this issue. Any solutions to this?

**Comment by pors** [comment]
It is most likely caused by:

> Are you using {...this.props} or cloneElement(element, this.props)? Your component is transferring its own props directly to a child element (eg. https://facebook.github.io/react/docs/transferring-props.html). 
> When transferring props to a child component, you should ensure that you are not accidentally forwarding props that were intended to be interpreted by the parent component.

Are you seeing these warnings with the kitchen sink app?
If not, please provide some more context.

**Comment by DarrylD** [comment]
Moved to react 15.0 was an issue with 15.2

**Comment by chrisbolin** [comment]
hey @pors! Yes, this happens with the kitchen sink demo. Simply installing the demo did it for me.

```
modules.js:21375 Warning: Unknown props `customClasses`, `leftButton`, `rightButton`, `history`, `location`, `params`, `route`, `routeParams`, `routes`, `pageList` on <span> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in span (created by ReactTransitionGroup)
    in ReactTransitionGroup (created by ReactCSSTransitionGroup)
    in ReactCSSTransitionGroup (created by RouteCSSTransitionGroup)
    in RouteCSSTransitionGroup (created by IonNavBar)
    in div (created by IonNavBar)
    in IonNavBar (created by Layout)
    in div (created by IonSideMenuContent)
    in IonSideMenuContent (created by Layout)
    in div (created by IonSideMenuContainer)
    in IonSideMenuContainer (created by Layout)
    in Layout (created by RouterContext)
    in div (created by IonBody)
    in IonBody (created by App)
    in App (created by RouterContext)
    in RouterContext (created by Router)
    in Router
```

React 15.2.1.

**Comment by pors** [comment]
@chrisbolin Hmm, I experience it as well. Where does this suddenly come from I wonder? We didn't do any React updates. 

Anyway, this is something we should fix. It's much better practice to peel off props before passing the whole this.props down.

**Comment by JWPapi** [comment]
Im having the same issue with my project. But its just after I clone my own repo again and hit npm install after. So I think its due to a never version of react.

**Comment by JWPapi** [comment]
Ok checking the versions. Its not happening with react 15.1!

**Comment by pors** [comment]
@JWPapi can you try version 1.2.0-beta.0 of reactionic and see if that resolves it? Will make it a new non-beta version soon.

**Comment by JWPapi** [comment]
npm install reactionic@1.2.0-beta.0
nightscool@ C:\Users\jwagner\Documents\TEST\nightscool
`-- reactionic@1.2.0-beta.0  invalid

**Comment by pors** [comment]
can you try: `npm install reactionic@beta`

**Comment by JWPapi** [comment]
same

Mark Pors notifications@github.com schrieb am Do., 11. Aug. 2016 um
12:15 Uhr:

**Comment by gabrielseco** [comment]
If you updated your app and the error shows, can you remove node_modules and install again.

In case that wouldn't work, could you upload a repo reproducing the problem.

**Comment by JWPapi** [comment]
https://github.com/JWPapi/nightscool

This repo comes without node_modules

You wont see much since its based on the DB, but you should get the error after cloning and npm install

**Comment by gabrielseco** [comment]
I made the next changes to make it work.

In package.json I updated reactionic.

```
    "reactionic": "1.2.0-beta.0"
```

And in ui/components/views/Reservation.jsx in line 89 replace the attribute in the label class for className.

Then do a npm install and it should work now.

**Comment by JWPapi** [comment]
Ok Thank you very much. Im really busy today. Will check it tomorrow and give feedback.

**Comment by JWPapi** [comment]
Ok im not getting the warning for unknown properties anymore. Im no having this error:

Warning: You are manually calling a React.PropTypes validation function for the `getComponents` prop on `IndexRoute`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

But I think that might be an issue with my project.  Sorry really in a hurry today

**Comment by CodeJjang** [comment]
Any fix? Still receiving this error today and it's very annoying.

**Comment by JWPapi** [comment]
The fix pors and gabrielseco mentioned are working. Anyway im Sorry, but Reactionic is not maintained anymore. You could try Onsen, if you not already put in a lot of effort
